### ISSUE TITLE
Update ScriptKit for an existing command line project

### ISSUE THREAD

**Issue by jbmaxwell** [TofPlay/XcodeTool#1]
After updating Xcode I'm getting this error: `... Module file was created by an older version of the compiler; rebuild '<...>' and try again` 

How do I rebuild my ScriptKit framework for an existing command line project, made with XcodeTool?

[EDIT: Ah, sorry... false alarm. I had to rebuild my custom framework separately. It's compiling now. Sorry for the spam!]

**Comment by TofPlay** [comment]
> Ah, sorry... false alarm
No problem 🙂
I close this ticket
